---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://SonarSource.github.io/helm-chart-sonarqube

