---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 30s
  url: https://SonarSource.github.io/helm-chart-sonarqube

